a = {"mylu","khanush"}
print(a)
b = {"ch","abhijith"}
print(b)
a.remove("mylu")
print(a)
a.add("asset")
print(a)
c = a.intersection(b)
print(c)
print(a.union(b))
a.add("mylu")
print(a)
print(len(a))
a.discard("mylu")
print(a)
y = a.isdisjoint(b)
print(y)
z = a.issubset(b)
print(z)
# x = a.difference(b)
# print(a)